# Generated by Django 3.1.2 on 2020-11-29 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('permissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=120, verbose_name='Word')),
            ],
        ),
        migrations.CreateModel(
            name='WikiPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('createdon', models.DateTimeField(auto_now_add=True, verbose_name='Created time')),
                ('updatedon', models.DateTimeField(auto_now_add=True, verbose_name='Updated time')),
                ('commonknowledge', models.BooleanField(default=False, verbose_name='Is common knowledge?')),
                ('title', models.CharField(max_length=160, verbose_name='Title*')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Article text')),
                ('createdby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='createdwikiarticles', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('keywords', models.ManyToManyField(to='wiki.Keywords', verbose_name='Keywords')),
                ('updatedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lastupdatedwikiarticles', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
        ),
        migrations.CreateModel(
            name='WikiSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('createdon', models.DateTimeField(auto_now_add=True, verbose_name='Created time')),
                ('updatedon', models.DateTimeField(auto_now_add=True, verbose_name='Updated time')),
                ('pageorder', models.IntegerField(verbose_name='Order*')),
                ('title', models.CharField(max_length=160, verbose_name='Title*')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Description of the issue')),
                ('createdby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='createdwikisections', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updatedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lastupdatedwikisections', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('wikipage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiki.wikipage')),
            ],
        ),
        migrations.CreateModel(
            name='PermissionSection',
            fields=[
                ('permission_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='permissions.permission')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='wiki.wikisection')),
            ],
            bases=('permissions.permission',),
        ),
    ]
