# Generated by Django 3.1.2 on 2020-12-13 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikisection',
            name='commonknowledge',
            field=models.BooleanField(default=False, verbose_name='Is common knowledge?'),
        ),
    ]
