# Generated by Django 3.1.2 on 2020-12-26 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0001_initial'),
        ('wiki', '0002_wikisection_commonknowledge'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionPage',
            fields=[
                ('permission_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='permissions.permission')),
                ('wikipage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='wiki.wikipage')),
            ],
            bases=('permissions.permission',),
        ),
    ]
