# Generated by Django 3.1.2 on 2020-11-29 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdon', models.DateTimeField(auto_now_add=True, verbose_name='Created time')),
                ('accesslevel', models.IntegerField(choices=[(0, 'Denied'), (10, 'View Only'), (20, 'Change Permissions'), (30, 'Edit')], verbose_name='Access Level*')),
                ('createdby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='createdpermissions', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('grantedto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apppermissions', to=settings.AUTH_USER_MODEL, verbose_name='Granted to')),
            ],
        ),
    ]
