# Generated by Django 3.1.2 on 2020-12-25 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CCalendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstyear', models.IntegerField(verbose_name='First year')),
            ],
        ),
        migrations.CreateModel(
            name='CWeek',
            fields=[
                ('calendar', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='week', serialize=False, to='customcalendar.ccalendar', verbose_name='Calendar settings')),
            ],
        ),
        migrations.CreateModel(
            name='CMonth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberofdays', models.IntegerField(verbose_name='Number of days a month')),
                ('monthnumber', models.IntegerField(verbose_name='Month number')),
                ('monthname', models.CharField(max_length=30, verbose_name='Month name:')),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='months', to='customcalendar.ccalendar', verbose_name='Calendar settings')),
            ],
        ),
        migrations.CreateModel(
            name='CWeekDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dayname', models.CharField(max_length=30, verbose_name='Week day name:')),
                ('daynumber', models.IntegerField(verbose_name='Week day number')),
                ('workday', models.BooleanField(default=True, verbose_name='Workday:')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='customcalendar.cweek', verbose_name='Week settings')),
            ],
        ),
    ]
