# Generated by Django 3.1.2 on 2021-01-01 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customcalendar', '0002_auto_20201225_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='CEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('eventday', models.IntegerField(verbose_name='Event Day')),
                ('eventmonth', models.IntegerField(verbose_name='Event Month')),
                ('eventyear', models.IntegerField(verbose_name='Event Year')),
                ('createdon', models.DateTimeField(auto_now_add=True, verbose_name='Created time')),
                ('updatedon', models.DateTimeField(auto_now_add=True, verbose_name='Updated time')),
                ('commonknowledge', models.BooleanField(default=False, verbose_name='Is common knowledge?')),
                ('title', models.CharField(max_length=160, verbose_name='Title*')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Article text')),
                ('createdby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='createdcalendarevents', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updatedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lastupdatedcalendarevents', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
        ),
        migrations.CreateModel(
            name='PermissionCEvent',
            fields=[
                ('permission_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='permissions.permission')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='customcalendar.cevent')),
            ],
            bases=('permissions.permission',),
        ),
    ]
