# Generated by Django 3.1.2 on 2021-01-02 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customcalendar', '0003_cevent_permissioncevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='cevent',
            name='eventtype',
            field=models.IntegerField(choices=[(0, 'History event'), (10, 'Holiday'), (20, 'Party event'), (30, 'Personal event')], default=0, verbose_name='Event Types'),
        ),
    ]
